version: '3'
services:
  web:
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - mysql
    links:
      - mysql:db
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "88:80"
    links:
      - mysql:db
  mysql:
    image: "mysql:5.6"
    volumes:
      - ./data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"